# dnf.conf - Configuración de DNF para Termux
[main]
gpgcheck=True
installonly_limit=3
clean_requirements_on_remove=True
best=False
skip_if_unavailable=True

# Termux-specific paths
cachedir=@PREFIX@/var/cache/dnf
pluginconfpath=@PREFIX@/etc/dnf/plugins
persistdir=@PREFIX@/var/lib/dnf
system_state_dir=@PREFIX@/var/lib/dnf
transaction_lock=@PREFIX@/var/lib/dnf/lock
varsdir=@PREFIX@/etc/dnf/vars

# Repositories
reposdir=@PREFIX@/etc/yum.repos.d
vendor_conf_dir=@PREFIX@/etc/yum.repos.d
