TERMUX_PKG_HOMEPAGE=https://github.com/openSUSE/libsolv
TERMUX_PKG_DESCRIPTION="Library for solving packages and reading repositories"
TERMUX_PKG_LICENSE="BSD-3-Clause"
TERMUX_PKG_LICENSE_FILE="LICENSE.BSD"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=0.7.39
TERMUX_PKG_SRCURL=https://github.com/openSUSE/libsolv/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=2a74cbf1e49984cb01f75ac4b19a237f24de6ce199766858aeb9ab3aae2b95fa
TERMUX_PKG_DEPENDS="zlib, rpm"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="-DENABLE_RPMMD=ON -DENABLE_COMPS=ON -DENABLE_DEBIAN=ON -DENABLE_LZMA_COMPRESSION=ON -DENABLE_ZSTD_COMPRESSION=ON -DENABLE_BZIP2_COMPRESSION=ON -DENABLE_STATIC=OFF -DENABLE_PERL=OFF -DENABLE_PYTHON=OFF -DENABLE_RUBY=OFF -DENABLE_TCL=OFF -DENABLE_LUA=OFF -DENABLE_RPMDB=ON"
